package org.book2words.dao;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import org.book2words.models.LibraryDictionary;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig libraryBookDaoConfig;

    private final LibraryBookDao libraryBookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        libraryBookDaoConfig = daoConfigMap.get(LibraryBookDao.class).clone();
        libraryBookDaoConfig.initIdentityScope(type);

        libraryBookDao = new LibraryBookDao(libraryBookDaoConfig, this);

        registerDao(LibraryBook.class, libraryBookDao);
    }
    
    public void clear() {
        libraryBookDaoConfig.getIdentityScope().clear();
    }

    public LibraryBookDao getLibraryBookDao() {
        return libraryBookDao;
    }

}
